# Generated by Django 3.1.3 on 2020-11-27 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_announcementmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
